Window.prototype.parseInt;
Window.prototype.document;
Window.prototype.screen;
Window.prototype.screen.width;
Window.prototype.screen.height;
Window.prototype.requestAnimationFrame;
Window.prototype.webkitRequestAnimationFrame;
Window.prototype.mozRequestAnimationFrame;
Window.prototype.msRequestAnimationFrame;
Object.defaultValue;
Object.onChange;
Object.charCodeAt;
Object.Fragment;
Object.index;
Object.firstElementChild;
Object.firstElementChild.remove;
Object.exec;
Object.value;
Object.findDOMNode;
Object.Component;
Object.Component.call;
Object.type;
Object.Children;
Object.Children.toArray;
Object.style;
Object.style.display;
Object.processing_obj;
Object.innerHTML;
Object.render;
Object.setAttribute;
Object.out;
Object.out.println;
Object.id;
Object.createElement;
Object.createElement.apply;
Object.appendChild;
Object.unmountComponentAtNode;
Object.error;
Object.error.println;
Object.hasOwnProperty;
HTMLDocument.prototype.fullscreenElement;
HTMLDocument.prototype.mozFullScreenElement;
HTMLDocument.prototype.getElementById;
HTMLDocument.prototype.createElement;
HTMLDocument.prototype.activeElement;
var RESULT;
RESULT.prototype.then;
var process;
process.hrtime;
var p5;
p5.prototype.quil_canvas;
p5.Shader;
p5.Image;
var setTimeout;
var gd;
gd.Treemap;
gd.Treemap.prototype.addData;
gd.Treemap.prototype.calculate;
HTMLBodyElement.prototype.childNodes;
HTMLBodyElement.prototype.childNodes.length;
HTMLBodyElement.prototype.appendChild;
var React;
React.Component;
React.Component.prototype.forceUpdate;
React.Component.prototype.cljsIsDirty;
React.Component.prototype.constructor$;
React.Component.prototype.props;
React.Component.prototype.props.argv;
React.Component.prototype.props.children;
var Java;
Java.type;
