// Compiled by ClojureScript 1.10.339 {:static-fns true, :optimize-constants true}
goog.provide('sketches.creative_coding.core');
goog.require('cljs.core');
goog.require('cljs.core.constants');
goog.require('sketches.components');
goog.require('sketches.creative_coding.print_art');
goog.require('sketches.creative_coding.webgl');
sketches.creative_coding.core.main = (function sketches$creative_coding$core$main(){
return new cljs.core.PersistentVector(null, 3, 5, cljs.core.PersistentVector.EMPTY_NODE, [cljs.core.cst$kw$_LT__GT_,new cljs.core.PersistentVector(null, 3, 5, cljs.core.PersistentVector.EMPTY_NODE, [sketches.components.section,"Creative Coding with Canvas & WebGL",new cljs.core.PersistentVector(null, 6, 5, cljs.core.PersistentVector.EMPTY_NODE, [cljs.core.cst$kw$_LT__GT_,"Sketches of ",new cljs.core.PersistentVector(null, 3, 5, cljs.core.PersistentVector.EMPTY_NODE, [cljs.core.cst$kw$a$pointer$bb$link$white,new cljs.core.PersistentArrayMap(null, 1, [cljs.core.cst$kw$href,"https://twitter.com/mattdesl"], null),"Matt DesLauriers'"], null)," ",new cljs.core.PersistentVector(null, 3, 5, cljs.core.PersistentVector.EMPTY_NODE, [cljs.core.cst$kw$a$pointer$bb$link$white,new cljs.core.PersistentArrayMap(null, 1, [cljs.core.cst$kw$href,"https://frontendmasters.com/courses/canvas-webgl/"], null),"Creative Coding with Canvas & WebGL"], null)," implemented in ClojureScript."], null)], null),new cljs.core.PersistentVector(null, 2, 5, cljs.core.PersistentVector.EMPTY_NODE, [sketches.components.cards_container,new cljs.core.PersistentVector(null, 3, 5, cljs.core.PersistentVector.EMPTY_NODE, [cljs.core.cst$kw$_LT__GT_,new cljs.core.PersistentVector(null, 5, 5, cljs.core.PersistentVector.EMPTY_NODE, [sketches.components.exercise_card,"01","Print Art with Canvas","https://frontendmasters.com/courses/canvas-webgl/",sketches.creative_coding.print_art.run], null),new cljs.core.PersistentVector(null, 5, 5, cljs.core.PersistentVector.EMPTY_NODE, [sketches.components.exercise_card,"02","WebGL","https://frontendmasters.com/courses/canvas-webgl/",sketches.creative_coding.webgl.run], null)], null)], null)], null);
});
