// Compiled by ClojureScript 1.10.339 {:static-fns true, :optimize-constants true}
goog.provide('sketches.nature_of_code.introduction.core');
goog.require('cljs.core');
goog.require('cljs.core.constants');
goog.require('sketches.components');
goog.require('sketches.nature_of_code.introduction.noise_animate');
goog.require('sketches.nature_of_code.introduction.noise_detail');
goog.require('sketches.nature_of_code.introduction.noise_terrain');
goog.require('sketches.nature_of_code.introduction.paint_splatter');
goog.require('sketches.nature_of_code.introduction.random_walk');
goog.require('sketches.nature_of_code.introduction.random_walk_custom_step');
goog.require('sketches.nature_of_code.introduction.random_walk_dynamic');
goog.require('sketches.nature_of_code.introduction.random_walk_gaussian');
goog.require('sketches.nature_of_code.introduction.random_walk_noise');
sketches.nature_of_code.introduction.core.main = (function sketches$nature_of_code$introduction$core$main(){
return new cljs.core.PersistentVector(null, 3, 5, cljs.core.PersistentVector.EMPTY_NODE, [cljs.core.cst$kw$div,new cljs.core.PersistentVector(null, 2, 5, cljs.core.PersistentVector.EMPTY_NODE, [cljs.core.cst$kw$h3$tracked$tc$tl_DASH_ns,"Introduction"], null),new cljs.core.PersistentVector(null, 2, 5, cljs.core.PersistentVector.EMPTY_NODE, [sketches.components.cards_container,new cljs.core.PersistentVector(null, 10, 5, cljs.core.PersistentVector.EMPTY_NODE, [cljs.core.cst$kw$_LT__GT_,new cljs.core.PersistentVector(null, 5, 5, cljs.core.PersistentVector.EMPTY_NODE, [sketches.components.exercise_card,"Random Walk","Exercise I.1","https://natureofcode.com/book/introduction/#exercise-i1",sketches.nature_of_code.introduction.random_walk.run], null),new cljs.core.PersistentVector(null, 5, 5, cljs.core.PersistentVector.EMPTY_NODE, [sketches.components.exercise_card,"Random Walk II","Exercise I.3","https://natureofcode.com/book/introduction/#exercise-i3",sketches.nature_of_code.introduction.random_walk_dynamic.run], null),new cljs.core.PersistentVector(null, 5, 5, cljs.core.PersistentVector.EMPTY_NODE, [sketches.components.exercise_card,"Paint Splatter","Exercise I.4","https://natureofcode.com/book/introduction/#exercise-i4",sketches.nature_of_code.introduction.paint_splatter.run], null),new cljs.core.PersistentVector(null, 5, 5, cljs.core.PersistentVector.EMPTY_NODE, [sketches.components.exercise_card,"Random Walk III","Exercise I.5","https://natureofcode.com/book/introduction/#exercise-i5",sketches.nature_of_code.introduction.random_walk_gaussian.run], null),new cljs.core.PersistentVector(null, 5, 5, cljs.core.PersistentVector.EMPTY_NODE, [sketches.components.exercise_card,"Random Walk IV","Exercise I.6","https://natureofcode.com/book/introduction/#exercise-i6",sketches.nature_of_code.introduction.random_walk_custom_step.run], null),new cljs.core.PersistentVector(null, 5, 5, cljs.core.PersistentVector.EMPTY_NODE, [sketches.components.exercise_card,"Random Walk V","Exercise I.7","https://natureofcode.com/book/introduction/#exercise-i7",sketches.nature_of_code.introduction.random_walk_noise.run], null),new cljs.core.PersistentVector(null, 5, 5, cljs.core.PersistentVector.EMPTY_NODE, [sketches.components.exercise_card,"Noise Detail","Exercise I.8","https://natureofcode.com/book/introduction/#exercise-i8",sketches.nature_of_code.introduction.noise_detail.run], null),new cljs.core.PersistentVector(null, 5, 5, cljs.core.PersistentVector.EMPTY_NODE, [sketches.components.exercise_card,"Noise Animate","Exercise I.9","https://natureofcode.com/book/introduction/#exercise-i9",sketches.nature_of_code.introduction.noise_animate.run], null),new cljs.core.PersistentVector(null, 5, 5, cljs.core.PersistentVector.EMPTY_NODE, [sketches.components.exercise_card,"Noise Terrain","Exercise I.10","https://natureofcode.com/book/introduction/#exercise-i10",sketches.nature_of_code.introduction.noise_terrain.run], null)], null)], null)], null);
});
