// Compiled by ClojureScript 1.10.339 {:static-fns true, :optimize-constants true}
goog.provide('sketches.nature_of_code.forces.core');
goog.require('cljs.core');
goog.require('cljs.core.constants');
goog.require('sketches.components');
goog.require('sketches.nature_of_code.forces.balloon');
goog.require('sketches.nature_of_code.forces.fluid');
goog.require('sketches.nature_of_code.forces.force_push');
goog.require('sketches.nature_of_code.forces.frictions');
goog.require('sketches.nature_of_code.forces.invisible_attractors');
goog.require('sketches.nature_of_code.forces.own_force');
goog.require('sketches.nature_of_code.forces.repulse_mouse');
goog.require('sketches.nature_of_code.forces.surface_area');
sketches.nature_of_code.forces.core.main = (function sketches$nature_of_code$forces$core$main(){
return new cljs.core.PersistentVector(null, 3, 5, cljs.core.PersistentVector.EMPTY_NODE, [cljs.core.cst$kw$div,new cljs.core.PersistentVector(null, 2, 5, cljs.core.PersistentVector.EMPTY_NODE, [cljs.core.cst$kw$h3$tracked$tc$tl_DASH_ns,"Forces"], null),new cljs.core.PersistentVector(null, 2, 5, cljs.core.PersistentVector.EMPTY_NODE, [sketches.components.cards_container,new cljs.core.PersistentVector(null, 9, 5, cljs.core.PersistentVector.EMPTY_NODE, [cljs.core.cst$kw$_LT__GT_,new cljs.core.PersistentVector(null, 5, 5, cljs.core.PersistentVector.EMPTY_NODE, [sketches.components.exercise_card,"Balloon","Exercise 2.1","https://natureofcode.com/book/chapter-2-forces#chapter02_exercise1",sketches.nature_of_code.forces.balloon.run], null),new cljs.core.PersistentVector(null, 5, 5, cljs.core.PersistentVector.EMPTY_NODE, [sketches.components.exercise_card,"Force Push","Exercise 2.3","https://natureofcode.com/book/chapter-2-forces#chapter02_exercise3",sketches.nature_of_code.forces.force_push.run], null),new cljs.core.PersistentVector(null, 5, 5, cljs.core.PersistentVector.EMPTY_NODE, [sketches.components.exercise_card,"Frictions","Exercise 2.4","https://natureofcode.com/book/chapter-2-forces#chapter02_exercise4",sketches.nature_of_code.forces.frictions.run], null),new cljs.core.PersistentVector(null, 5, 5, cljs.core.PersistentVector.EMPTY_NODE, [sketches.components.exercise_card,"Fluid","Exercise 2.5","https://natureofcode.com/book/chapter-2-forces#chapter02_exercise5",sketches.nature_of_code.forces.fluid.run], null),new cljs.core.PersistentVector(null, 5, 5, cljs.core.PersistentVector.EMPTY_NODE, [sketches.components.exercise_card,"Surface Area","Exercise 2.6","https://natureofcode.com/book/chapter-2-forces#chapter02_exercise6",sketches.nature_of_code.forces.surface_area.run], null),new cljs.core.PersistentVector(null, 5, 5, cljs.core.PersistentVector.EMPTY_NODE, [sketches.components.exercise_card,"Invisible Attractors","Exercise 2.8","https://natureofcode.com/book/chapter-2-forces#chapter02_exercise8",sketches.nature_of_code.forces.invisible_attractors.run], null),new cljs.core.PersistentVector(null, 5, 5, cljs.core.PersistentVector.EMPTY_NODE, [sketches.components.exercise_card,"Own Force","Exercise 2.9","https://natureofcode.com/book/chapter-2-forces#chapter02_exercise9",sketches.nature_of_code.forces.own_force.run], null),new cljs.core.PersistentVector(null, 5, 5, cljs.core.PersistentVector.EMPTY_NODE, [sketches.components.exercise_card,"Repulse Mouse","Exercise 2.10","https://natureofcode.com/book/chapter-2-forces#chapter02_exercise10",sketches.nature_of_code.forces.repulse_mouse.run], null)], null)], null)], null);
});
