name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Install dep
      run: |
        curl -O https://download.clojure.org/install/linux-install-1.10.1.469.sh
        chmod +x linux-install-1.10.1.469.sh
        sudo ./linux-install-1.10.1.469.sh
    - name: Build
      run: |
        clojure -m figwheel.main -O advanced -bo dev
        cp -r resources/public/* target/public/
    - uses: maxheld83/ghpages@v0.2.1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BUILD_DIR: "target/public"
