name: CI/CD

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Clojure install
      run: |
        curl -O https://download.clojure.org/install/linux-install-1.10.1.469.sh
        chmod +x linux-install-1.10.1.469.sh
        sudo ./linux-install-1.10.1.469.sh
    - name: Use Node.js
      uses: actions/setup-node@v1
    - name: npm install
      run: npm install
    - name: Build JS
      run: npx shadow-cljs release app
    - name: Deploy 🚀
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        folder: public
